---
name: eden-${NETWORK}

services:
  jwt-init:
    image: &alpine ghcr.io/linuxserver/baseimage-alpine:3.22
    volumes:
      - jwttoken:/jwt
    healthcheck:
      test: [CMD, test, -f, /jwt/jwt.hex]
      interval: 5s
      timeout: 5s
      retries: 3
    command: >
      /bin/sh -c "mkdir -p /jwt &&
      if [ ! -f /jwt/jwt.hex ]; then
        apk add --no-cache openssl &&
        openssl rand -hex 32 | tr -d '\n' > /jwt/jwt.hex;
      fi"

  init-1-snapshot-ev-reth:
    image: *alpine
    env_file: .env
    volumes:
      - ./ev-reth.genesis.json:/root/genesis.json:ro
      - jwttoken:/root/jwt:ro
      - ev-reth-data:/root/reth
      - ./init-1-ev-reth-snapshot.sh:/init-1-ev-reth-snapshot.sh
    entrypoint: [/bin/sh, /init-1-ev-reth-snapshot.sh]
    restart: "no"
    depends_on:
      init-1-ev-node:
        condition: service_completed_successfully

  init-1-ev-node:
    image: &image ghcr.io/evstack/ev-node-evm:v1.1.4
    env_file: .env
    volumes:
      - ev-node-data:/root/.evm
      - ./ev-node.genesis.json:/volumes/sequencer_export/genesis.json:ro
      - ./ev-reth.genesis.json:/root/genesis.json:ro
      - jwttoken:/root/jwt:ro
      - ./init-1-ev-node.sh:/init-1-ev-node.sh
    entrypoint: [/bin/sh, /init-1-ev-node.sh]
    restart: "no"

  init-2-snapshot-ev-node:
    image: *alpine
    env_file: .env
    volumes:
      - ev-node-data:/root/.evm
      - ./ev-node.genesis.json:/volumes/sequencer_export/genesis.json:ro
      - ./ev-reth.genesis.json:/root/genesis.json:ro
      - jwttoken:/root/jwt:ro
      - ./init-2-ev-node-snapshot.sh:/init-2-ev-node-snapshot.sh
    entrypoint: [/bin/bash, /init-2-ev-node-snapshot.sh]
    restart: "no"
    depends_on:
      init-1-ev-node:
        condition: service_completed_successfully

  ev-reth:
    image: ghcr.io/evstack/ev-reth:v0.4.1
    depends_on:
      jwt-init:
        condition: service_completed_successfully
      init-1-snapshot-ev-reth:
        condition: service_completed_successfully
    env_file: .env
    network_mode: host
    restart: always
    volumes:
      - ./ev-reth.genesis.json:/root/genesis.json:ro
      - jwttoken:/root/jwt:ro
      - ev-reth-data:/root/reth
    entrypoint: /bin/sh -c
    command:
      - |
        ev-reth node \
        --engine.persistence-threshold 0 \
        --engine.memory-block-buffer-target 0 \
        --engine.always-process-payload-attributes-on-canonical-head \
        --chain /root/genesis.json \
        --metrics 0.0.0.0:${EV_RETH_PROMETHEUS_PORT} \
        --log.file.directory /root/logs \
        --authrpc.addr 0.0.0.0 \
        --authrpc.port ${EV_RETH_ENGINE_PORT} \
        --authrpc.jwtsecret /root/jwt/jwt.hex \
        --http --http.addr 0.0.0.0 --http.port ${EV_RETH_RPC_PORT} \
        --http.api "eth,net,web3,txpool" \
        --ws --ws.addr 0.0.0.0 --ws.port ${EV_RETH_WS_PORT} \
        --port ${EV_RETH_DISCOVERY_PORT} \
        --disable-discovery \
        --trusted-peers ${EV_RETH_TRUSTED_PEERS} \
        --txpool.pending-max-count 200000 \
        --txpool.pending-max-size 200 \
        --txpool.queued-max-count 200000 \
        --txpool.queued-max-size 200 \
        --txpool.max-account-slots 2048 \
        --txpool.max-new-txns 2048 \
        --txpool.additional-validation-tasks 16 \
        --datadir /root/reth
    healthcheck:
      test:
        [
          CMD,
          curl,
          -X,
          POST,
          -H,
          "Content-Type: application/json",
          --data,
          '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}',
          "http://localhost:${EV_RETH_RPC_PORT}",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

  ev-node:
    image: *image
    env_file: .env
    network_mode: host
    restart: always
    depends_on:
      ev-reth:
        condition: service_started
      init-2-snapshot-ev-node:
        condition: service_completed_successfully
    volumes:
      - ev-node-data:/root/.evm
      - ./ev-node.genesis.json:/volumes/sequencer_export/genesis.json:ro
      - ./ev-reth.genesis.json:/root/genesis.json:ro
      - jwttoken:/root/jwt:ro
      - ./entrypoint.fullnode.sh:/usr/bin/entrypoint.sh
    command:
      - start
      - --evnode.rpc.address=0.0.0.0:${EV_NODE_RPC_PORT}
      - --evnode.instrumentation.prometheus
      - --evnode.instrumentation.prometheus_listen_addr=:${EV_NODE_PROMETHEUS_PORT}
      - --evnode.p2p.listen_address=/ip4/0.0.0.0/tcp/7676
      - --evnode.p2p.peers=${EV_NODE_P2P_PEERS}
      # - --evnode.log.level=debug
    environment:
      - DA_HEADER_NAMESPACE=${DA_HEADER_NAMESPACE}
      - DA_DATA_NAMESPACE=${DA_DATA_NAMESPACE}
      - EVM_ENGINE_URL=http://${EV_RETH_ADDRESS}:${EV_RETH_ENGINE_PORT}
      - EVM_ETH_URL=http://${EV_RETH_ADDRESS}:${EV_RETH_RPC_PORT}
      - EVM_JWT_SECRET_FILE=/root/jwt/jwt.hex
    healthcheck:
      test: [CMD, curl, "localhost:${EV_NODE_RPC_PORT}/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  ev-node-data:
    driver: local
  ev-reth-data:
    driver: local
  jwttoken:
    driver: local
